version: '3'
services:
  postgres:
    image: postgres:16.0-bullseye
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./build/docker/postgres/data:/var/lib/postgresql/data
      - ./build/docker/postgres/init:/docker-entrypoint-initdb.d
