version: '3'

env:
  GQLGEN_VERSION: v0.17.39
  GO_VERSION: 1.21.1
  GO: "go{{.GO_VERSION}}"
  LINT_VERSION: v1.54.2

tasks:
  run:
    desc: server を起動
    cmds:
      - "{{.GO}} run cmd/main.go"

  gqlgen:
    desc: gqlgen generate を実行
    cmds:
      - "{{.GO}} run github.com/99designs/gqlgen@{{.GQLGEN_VERSION}} generate --verbose"

  fmt:
    desc: go fmt を実行
    cmds:
      - "{{.GO}} fmt ./internal/..."

  lint:
    desc: golangci-lint run を実行
    cmds:
      - golangci-lint run --verbose --config .golangci.yml

  install-tools:
    desc: 必要なツールをまとめてインストール
    cmds:
      - task install-go
      - task install-lint
  
  install-go:
    desc: go{{.GO_VERSION}} をインストール
    cmds:
      - go install golang.org/dl/{{.GO}}@latest
      - "{{.GO}} download"

  install-lint:
    desc: golangci-lint{{.LINT_VERSION}} をインストール
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@{{.LINT_VERSION}}

  docker-init:
    desc: Dockerコンテナを初期化
    cmds:
      - task docker-down
      - task docker-build
      - task docker-up

  docker-build:
    cmds: 
      - docker-compose build --no-cache

  docker-up:
    cmds: 
      - docker-compose up -d

  docker-down:
    cmds:
      - docker-compose down