package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"html"

	"github.com/hareta0109/graphql_sandbox/internal/domain/model/graph"
)

// CreateDepartment is the resolver for the createDepartment field.
func (r *mutationResolver) CreateDepartment(ctx context.Context, input graph.DepartmentCreateInput) (*graph.Department, error) {
	escapedName := html.EscapeString(input.Name)
	department, err := r.DepartmentUsecase.Create(escapedName)
	if err != nil {
		return nil, err
	}

	return department, nil
}

// Department is the resolver for the department field.
func (r *queryResolver) Department(ctx context.Context, id uint64) (*graph.Department, error) {
	department, err := r.DepartmentUsecase.Get(id)
	if err != nil {
		return nil, err
	}

	return department, nil
}

// Departments is the resolver for the departments field.
func (r *queryResolver) Departments(ctx context.Context) ([]*graph.Department, error) {
	departments, err := r.DepartmentUsecase.BulkGet()
	if err != nil {
		return nil, err
	}

	return departments, nil
}
