package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"
	"fmt"

	"github.com/hareta0109/graphql_sandbox/internal/graph/generated"
)

// MutationQuery is the resolver for the mutationQuery field.
func (r *mutationResolver) MutationQuery(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: MutationQuery - mutationQuery"))
}

// HelloQuery is the resolver for the helloQuery field.
func (r *queryResolver) HelloQuery(ctx context.Context) (string, error) {
	panic(fmt.Errorf("not implemented: HelloQuery - helloQuery"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
