// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Department struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`
}

type DepartmentCreateInput struct {
	Name string `json:"name"`
}

type TodoCreateInput struct {
	Text   string `json:"text"`
	UserID uint64 `json:"userId"`
}

type UserCreateInput struct {
	Name         string `json:"name"`
	DepartmentID uint64 `json:"departmentId"`
}
